apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-manager-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  APT_ENABLED: {{ .Values.managerConfig.aptEnabled | quote }}
  HOSTFS_ENABLED: {{ .Values.managerConfig.hostfsEnabled | quote }}
  VALIDATION_MODULE_PRESENT_ENABLED: {{ .Values.managerConfig.validationModulePresentEnabled
    | quote }}