apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-serving-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-configuration-whitestack-com-v1beta2-nodeconfig
  failurePolicy: Fail
  name: vnodeconfig.kb.io
  rules:
  - apiGroups:
    - configuration.whitestack.com
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodeconfigs
  sideEffects: None