# permissions for end users to view nodeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodeconfig-viewer-role
rules:
- apiGroups:
  - configuration.whitestack.com
  resources:
  - nodeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.whitestack.com
  resources:
  - nodeconfigs/status
  verbs:
  - get
