apiVersion: configuration.whitestack.com/v1beta1
kind: NodeConfig
metadata:
  labels:
    app.kubernetes.io/name: nodeconfig
    app.kubernetes.io/instance: nodeconfig-sample
    app.kubernetes.io/part-of: node-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: node-config-operator
  name: nodeconfig-sample
spec:
  nodeSelector:
  - key: "label-test"
    operator: In
    values:
    - "test"
  aptPackages:
    packages:
    - name: vim
    - name: ssh
      version: 1:9.6p1-3ubuntu13.5
    state: present
  kernelParameters:
    parameters:
    - name: kernel.hostname
      value: test-hostname
    state: present
    priority: 90
  kernelModules:
    modules:
    - multipath
    - dm_multipath
    state: present
  systemdUnits:
    units:
    - name: test-service
      file: |
        [Unit]
        Description=example systemd service unit file.

        [Service]
        ExecStart=/bin/bash -c "while true; do echo 'hello'; sleep 10; done"

        [Install]
        WantedBy=multi-user.target
    state: present
  systemdOverrides:
    overrides:
    - name: nco-test-service.service
      file: |-
        [Service]
        ExecStart=
        ExecStart=sleep 2000
        User=root
    state: present
  hosts:
    hosts:
    # you can add multiple entries for the same IP
    - hostname: "test.whitestack.com"
      ip: "10.0.0.1"
    - hostname: "test2.whitestack.com"
      ip: "10.0.0.1"
      # or multiple hostnames separated by spaces
    - hostname: "test3.whitestack.com test4.whitestack.com"
      ip: "10.0.0.3"
    state: present
  blockInFiles:
    blocks:
    - filename: "/etc/test.conf"
      content: |
        test1
        test2
      beginMarker: "# NCO BEGIN MARKER"
      endMarker: "# NCO END MARKER"
    state: present
