name: build-latest
on:
  push:
    branches:
    - "main"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: '=1.22.0'
    - name: Create image name with tag
      run: echo "IMG=ghcr.io/whitestack/node-config-operator:latest" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      run: make docker-build "IMG=${IMG}"
    - name: Push image
      run: make docker-push "IMG=${IMG}"
